/* generated by code template -- do no edit */
/* eslint-disable */

import type { BaseHttpRequest } from './core/BaseHttpRequest';


import { OpenAPIConfig } from './core/OpenAPI';
import { AxiosHttpRequest } from './core/AxiosHttpRequest';
import { AxiosInstance } from 'axios';
import { OauthService } from './services/OauthService';


export class OauthClient {
  public readonly oauth: OauthService;
  public readonly request: BaseHttpRequest;

  public static createInstance(config:OpenAPIConfig, instance: AxiosInstance){
    return new OauthClient(new AxiosHttpRequest(config, instance));
  }

  constructor(request: BaseHttpRequest) {
    this.request = request;
    this.oauth = new OauthService(this.request);
  }
}