name: build and release

on:
  workflow_dispatch:

jobs: 
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{matrix.node-version}}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
  