name: Code generate and create pull request

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs: 
  generate: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4.0.0
      with:
        node-version: ${{matrix.node-version}}
    - name: Cache dependencies
      uses: actions/cache@v3
      with: 
        path: '**/node_modules'
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5 
      with:
        token: ${{ secrets.PAT }}
        commit-message: code generate
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: main
        delete-branch: true
        branch-suffix: short-commit-hash
        title: '[Code gen] Update OpenApi files'
        body: |
          Update Files
        draft: false 

